baseURL = 'https://torstein.io/'
languageCode = 'en-us'
title = 'Torstein Norendal: Produkt- og prosjektleder'
theme = 'terminal'
paginate = 3

[params]
  contentTypeName = "posts"
  themeColor = "orange"
  showMenuItems = 0
  fullWidthTheme = false
  centerTheme = true
  css = ["css/style.css"]

[languages]
  [languages.en]
    title = "Torstein Norendal: Produkt- og prosjektleder"
    subtitle = "Tekster om det jeg gjør"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read on"
    readOtherPosts = "Read other posts"

  [languages.en.params.logo]
      logoText = "Torstein Norendal: Produkt- og prosjektleder"
      logoHomeLink = "/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
