baseURL = 'https://torstein.io/'
languageCode = 'en-us'
title = 'Torstein Norendal: Rådgiver for innhold og innsikt'
theme = 'terminal'
paginate = 3

[params]
  contentTypeName = "posts"
  themeColor = "orange"
  showMenuItems = 0
  fullWidthTheme = false
  centerTheme = true
  css = ["css/style.css"]

[languages]
  [languages.en]
    title = "Torstein Norendal: Rådgiver for innhold og innsikt"
    subtitle = "Tekster om det jeg gjør"
    keywords = ""
    copyright = ""
    #menuMore = "Vis innhold"
    readMore = "Read on"
    readOtherPosts = "Read other posts"

  [languages.en.params.logo]
      logoText = "Torstein Norendal: Rådgiver for innhold og innsikt"
      logoHomeLink = "/"

 
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
